# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Deploy WAR to local server
    - run: mkdir artifacts && cp target/*.war artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: artifacts
      #run: |
        # Transfer the WAR file to the Tomcat server using SCP or any other method.
       # scp -r *.war $SERVER_USERNAME@$SERVER_HOST:/$SERVER_USERNAME/github/
