# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - name: Deploy
      run: |
# Replace 'your_centos_server_ip' with the IP address or hostname of your CentOS server
# Replace 'your_war_file_path' with the path where you want to store the WAR file on the CentOS server
scp hello-world-war/dist/hello-world.war vishnulatha@192.168.60.76:/home/vishnulatha/hello-world-war/.github/workflows/artifacts
